export const HS_CODES = [
    { code: "0101", desc: "Live horses, asses, mules and hinnies" },
    { code: "0102", desc: "Live bovine animals" },
    { code: "0103", desc: "Live swine" },
    { code: "0104", desc: "Live sheep and goats" },
    { code: "0105", desc: "Live poultry, that is to say, fowls of the species Gallus domesticus, ducks, geese, turkeys and guinea fowls" },
    { code: "0201", desc: "Meat of bovine animals, fresh or chilled" },
    { code: "0202", desc: "Meat of bovine animals, frozen" },
    { code: "0203", desc: "Meat of swine, fresh, chilled or frozen" },
    { code: "0204", desc: "Meat of sheep or goats, fresh, chilled or frozen" },
    { code: "0207", desc: "Meat and edible offal, of the poultry of heading 0105, fresh, chilled or frozen" },
    { code: "0302", desc: "Fish, fresh or chilled, excluding fish fillets and other fish meat of heading 0304" },
    { code: "0303", desc: "Fish, frozen, excluding fish fillets and other fish meat of heading 0304" },
    { code: "0304", desc: "Fish fillets and other fish meat (whether or not minced), fresh, chilled or frozen" },
    { code: "0306", desc: "Crustaceans, whether in shell or not, live, fresh, chilled, frozen, dried, salted or in brine" },
    { code: "0401", desc: "Milk and cream, not concentrated nor containing added sugar or other sweetening matter" },
    { code: "0402", desc: "Milk and cream, concentrated or containing added sugar or other sweetening matter" },
    { code: "0406", desc: "Cheese and curd" },
    { code: "0504", desc: "Guts, bladders and stomachs of animals (other than fish), whole and pieces thereof, fresh, chilled, frozen, salted, in brine, dried or smoked" },
    { code: "0601", desc: "Bulbs, tubers, tuberous roots, corms, crowns and rhizomes, dormant, in growth or in flower; chicory plants and roots other than roots of heading 1212" },
    { code: "0602", desc: "Other live plants (including their roots), cuttings and slips; mushroom spawn" },
    { code: "0603", desc: "Cut flowers and flower buds of a kind suitable for bouquets or for ornamental purposes, fresh, dried, dyed, bleached, impregnated or otherwise prepared" },
    { code: "0701", desc: "Potatoes, fresh or chilled" },
    { code: "0702", desc: "Tomatoes, fresh or chilled" },
    { code: "0703", desc: "Onions, shallots, garlic, leeks and other alliaceous vegetables, fresh or chilled" },
    { code: "0704", desc: "Cabbages, cauliflowers, kohlrabi, kale and similar edible brassicas, fresh or chilled" },
    { code: "0705", desc: "Lettuce (Lactuca sativa) and chicory (Cichorium spp.), fresh or chilled" },
    { code: "0708", desc: "Leguminous vegetables, shelled or unshelled, fresh or chilled" },
    { code: "0709", desc: "Other vegetables, fresh or chilled" },
    { code: "0803", desc: "Bananas, including plantains, fresh or dried" },
    { code: "0804", desc: "Dates, figs, pineapples, avocados, guavas, mangoes and mangosteens, fresh or dried" },
    { code: "0805", desc: "Citrus fruit, fresh or dried" },
    { code: "0806", desc: "Grapes, fresh or dried" },
    { code: "0808", desc: "Apples, pears and quinces, fresh" },
    { code: "0810", desc: "Other fruit, fresh" },
    { code: "0901", desc: "Coffee, whether or not roasted or decaffeinated; coffee husks and skins; coffee substitutes containing coffee in any proportion" },
    { code: "0902", desc: "Tea, whether or not flavoured" },
    { code: "0904", desc: "Pepper of the genus Piper; dried or crushed or ground fruits of the genus Capsicum or of the genus Pimenta" },
    { code: "1001", desc: "Wheat and meslin" },
    { code: "1005", desc: "Maize (corn)" },
    { code: "1006", desc: "Rice" },
    { code: "1101", desc: "Wheat or meslin flour" },
    { code: "1201", desc: "Soya beans, whether or not broken" },
    { code: "1509", desc: "Olive oil and its fractions, whether or not refined, but not chemically modified" },
    { code: "1511", desc: "Palm oil and its fractions, whether or not refined, but not chemically modified" },
    { code: "1701", desc: "Cane or beet sugar and chemically pure sucrose, in solid form" },
    { code: "1806", desc: "Chocolate and other food preparations containing cocoa" },
    { code: "1905", desc: "Bread, pastry, cakes, biscuits and other bakers' wares, whether or not containing cocoa; communion wafers, empty cachets of a kind suitable for pharmaceutical use, sealing wafers, rice paper and similar products" },
    { code: "2103", desc: "Sauces and preparations therefor; mixed condiments and mixed seasonings; mustard flour and meal and prepared mustard" },
    { code: "2106", desc: "Food preparations not elsewhere specified or included" },
    { code: "2203", desc: "Beer made from malt" },
    { code: "2204", desc: "Wine of fresh grapes, including fortified wines; grape must other than that of heading 2009" },
    { code: "2208", desc: "Undenatured ethyl alcohol of an alcoholic strength by volume of less than 80 % vol; spirits, liqueurs and other spirituous beverages" },
    { code: "2402", desc: "Cigars, cheroots, cigarillos and cigarettes, of tobacco or of tobacco substitutes" },
    { code: "2523", desc: "Portland cement, aluminous cement, slag cement, supersulphate cement and similar hydraulic cements, whether or not coloured or in the form of clinkers" },
    { code: "2709", desc: "Petroleum oils and oils obtained from bituminous minerals, crude" },
    { code: "2710", desc: "Petroleum oils and oils obtained from bituminous minerals, other than crude; preparations not elsewhere specified or included, containing by weight 70 % or more of petroleum oils or of oils obtained from bituminous minerals, these oils being the basic constituents of the preparations; waste oils" },
    { code: "2711", desc: "Petroleum gases and other gaseous hydrocarbons" },
    { code: "3002", desc: "Human blood; animal blood prepared for therapeutic, prophylactic or diagnostic uses; antisera, other blood fractions and immunological products, whether or not modified or obtained by means of biotechnological processes; vaccines, toxins, cultures of micro-organisms (excluding yeasts) and similar products" },
    { code: "3004", desc: "Medicaments (excluding goods of heading 3002, 3005 or 3006) consisting of mixed or unmixed products for therapeutic or prophylactic uses, put up in measured doses (including those in the form of transdermal administration systems) or in forms or packings for retail sale" },
    { code: "3303", desc: "Perfumes and toilet waters" },
    { code: "3304", desc: "Beauty or make-up preparations and preparations for the care of the skin (other than medicaments), including sunscreen or sun tan preparations; manicure or pedicure preparations" },
    { code: "3401", desc: "Soap; organic surface-active products and preparations for use as soap, in the form of bars, cakes, moulded pieces or shapes, whether or not containing soap; organic surface-active products and preparations for washing the skin, in the form of liquid or cream and put up for retail sale, whether or not containing soap; paper, wadding, felt and nonwovens, impregnated, coated or covered with soap or detergent" },
    { code: "3808", desc: "Insecticides, rodenticides, fungicides, herbicides, anti-sprouting products and plant-growth regulators, disinfectants and similar products, put up in forms or packings for retail sale or as preparations or articles (for example, sulphur-treated bands, wicks and candles, and fly-papers)" },
    { code: "3901", desc: "Polymers of ethylene, in primary forms" },
    { code: "3917", desc: "Tubes, pipes and hoses, and fittings therefor (for example, joints, elbows, flanges), of plastics" },
    { code: "3923", desc: "Articles for the conveyance or packing of goods, of plastics; stoppers, lids, caps and other closures, of plastics" },
    { code: "3926", desc: "Other articles of plastics and articles of other materials of headings 3901 to 3914" },
    { code: "4011", desc: "New pneumatic tyres, of rubber" },
    { code: "4202", desc: "Trunks, suit-cases, vanity-cases, executive-cases, brief-cases, school satchels, spectacle cases, binocular cases, camera cases, musical instrument cases, gun cases, holsters and similar containers; travelling-bags, insulated food or beverages bags, toilet bags, rucksacks, handbags, shopping-bags, wallets, purses, map-cases, cigarette-cases, tobacco-pouches, tool bags, sports bags, bottle-cases, jewellery boxes, powder-boxes, cutlery cases and similar containers, of leather or of composition leather, of sheeting of plastics, of textile materials, of vulcanised fibre or of paperboard, or wholly or mainly covered with such materials or with paper" },
    { code: "4403", desc: "Wood in the rough, whether or not stripped of bark or sapwood, or roughly squared" },
    { code: "4407", desc: "Wood sawn or chipped lengthwise, sliced or peeled, whether or not planed, sanded or end-jointed, of a thickness exceeding 6 mm" },
    { code: "4703", desc: "Chemical wood pulp, soda or sulphate, other than dissolving grades" },
    { code: "4818", desc: "Toilet paper and similar paper, cellulose wadding or webs of cellulose fibres, of a kind used for household or sanitary purposes, in rolls of a width not exceeding 36 cm, or cut to size or shape; handkerchiefs, cleansing tissues, towels, tablecloths, serviettes, bed sheets and similar household, sanitary or hospital articles, articles of apparel and clothing accessories, of paper pulp, paper, cellulose wadding or webs of cellulose fibres" },
    { code: "4819", desc: "Cartons, boxes, cases, bags and other packing containers, of paper, paperboard, cellulose wadding or webs of cellulose fibres; box files, letter trays, and similar articles, of paper or paperboard of a kind used in offices, shops or the like" },
    { code: "4901", desc: "Printed books, brochures, leaflets and similar printed matter, whether or not in single sheets" },
    { code: "5201", desc: "Cotton, not carded or combed" },
    { code: "6109", desc: "T-shirts, singlets and other vests, knitted or crocheted" },
    { code: "6110", desc: "Jerseys, pullovers, cardigans, waistcoats and similar articles, knitted or crocheted" },
    { code: "6115", desc: "Panty hose, tights, stockings, socks and other hosiery, including graduated compression hosiery (for example, stockings for varicose veins) and footwear without applied soles, knitted or crocheted" },
    { code: "6203", desc: "Men's or boys' suits, ensembles, jackets, blazers, trousers, bib and brace overalls, breeches and shorts (other than swimwear)" },
    { code: "6204", desc: "Women's or girls' suits, ensembles, jackets, blazers, dresses, skirts, divided skirts, trousers, bib and brace overalls, breeches and shorts (other than swimwear)" },
    { code: "6302", desc: "Bed linen, table linen, toilet linen and kitchen linen" },
    { code: "6309", desc: "Worn clothing and other worn articles" },
    { code: "6402", desc: "Other footwear with outer soles and uppers of rubber or plastics" },
    { code: "6403", desc: "Footwear with outer soles of rubber, plastics, leather or composition leather and uppers of leather" },
    { code: "6404", desc: "Footwear with outer soles of rubber, plastics, leather or composition leather and uppers of textile materials" },
    { code: "6907", desc: "Ceramic flags and paving, hearth or wall tiles; ceramic mosaic cubes and the like, whether or not on a backing; finishing ceramics" },
    { code: "7108", desc: "Gold (including gold plated with platinum) unwrought or in semi-manufactured forms, or in powder form" },
    { code: "7113", desc: "Articles of jewellery and parts thereof, of precious metal or of metal clad with precious metal" },
    { code: "7204", desc: "Ferrous waste and scrap; remelting scrap ingots of iron or steel" },
    { code: "7208", desc: "Flat-rolled products of iron or non-alloy steel, of a width of 600 mm or more, hot-rolled, not clad, plated or coated" },
    { code: "7308", desc: "Structures (excluding prefabricated buildings of heading 9406) and parts of structures (for example, bridges and bridge-sections, lock-gates, towers, lattice masts, roofs, roofing frame-works, doors and windows and their frames and thresholds for doors, shutters, balustrades, pillars and columns), of iron or steel; plates, rods, angles, shapes, sections, tubes and the like, prepared for use in structures, of iron or steel" },
    { code: "7318", desc: "Screws, bolts, nuts, coach screws, screw hooks, rivets, cotters, cotter-pins, washers (including spring washers) and similar articles, of iron or steel" },
    { code: "7403", desc: "Refined copper and copper alloys, unwrought" },
    { code: "7601", desc: "Unwrought aluminium" },
    { code: "8407", desc: "Spark-ignition reciprocating or rotary internal combustion piston engines" },
    { code: "8408", desc: "Compression-ignition internal combustion piston engines (diesel or semi-diesel engines)" },
    { code: "8409", desc: "Parts suitable for use solely or principally with the engines of heading 8407 or 8408" },
    { code: "8411", desc: "Turbo-jets, turbo-propellers and other gas turbines" },
    { code: "8413", desc: "Pumps for liquids, whether or not fitted with a measuring device; liquid elevators" },
    { code: "8414", desc: "Air or vacuum pumps, air or other gas compressors and fans; ventilating or recycling hoods incorporating a fan, whether or not fitted with filters" },
    { code: "8415", desc: "Air conditioning machines, comprising a motor-driven fan and elements for changing the temperature and humidity, including those machines in which the humidity cannot be separately regulated" },
    { code: "8418", desc: "Refrigerators, freezers and other refrigerating or freezing equipment, electric or other; heat pumps other than air conditioning machines of heading 8415" },
    { code: "8419", desc: "Machinery, plant or laboratory equipment, whether or not electrically heated (excluding furnaces, ovens and other equipment of heading 8514), for the treatment of materials by a process involving a change of temperature such as heating, cooking, roasting, distilling, rectifying, sterilising, pasteurising, steaming, drying, evaporating, vaporising, condensing or cooling, other than machinery or plant of a kind used for domestic purposes; instantaneous or storage water heaters, non-electric" },
    { code: "8421", desc: "Centrifuges, including centrifugal dryers; filtering or purifying machinery and apparatus, for liquids or gases" },
    { code: "8428", desc: "Other lifting, handling, loading or unloading machinery (for example, lifts, escalators, conveyors, teleferics)" },
    { code: "8431", desc: "Parts suitable for use solely or principally with the machinery of headings 8425 to 8430" },
    { code: "8471", desc: "Automatic data processing machines and units thereof; magnetic or optical readers, machines for transcribing data onto data media in coded form and machines for processing such data, not elsewhere specified or included" },
    { code: "8473", desc: "Parts and accessories (other than covers, carrying cases and the like) suitable for use solely or principally with machines of headings 8470 to 8472" },
    { code: "8474", desc: "Machinery for sorting, screening, separating, washing, crushing, grinding, mixing or kneading earth, stone, ores or other mineral substances, in solid (including powder or paste) form; machinery for agglomerating, shaping or moulding solid mineral fuels, ceramic paste, unhardened cements, plastering materials or other mineral products in powder or paste form; machines for forming foundry moulds of sand" },
    { code: "8479", desc: "Machines and mechanical appliances having individual functions, not specified or included elsewhere in this Chapter" },
    { code: "8481", desc: "Taps, cocks, valves and similar appliances for pipes, boiler shells, tanks, vats or the like, including pressure-reducing valves and thermostatically controlled valves" },
    { code: "8482", desc: "Ball or roller bearings" },
    { code: "8501", desc: "Electric motors and generators (excluding generating sets)" },
    { code: "8502", desc: "Electric generating sets and rotary converters" },
    { code: "8504", desc: "Electrical transformers, static converters (for example, rectifiers) and inductors" },
    { code: "8507", desc: "Electric accumulators, including separators therefor, whether or not rectangular (including square)" },
    { code: "8517", desc: "Telephone sets, including telephones for cellular networks or for other wireless networks; other apparatus for the transmission or reception of voice, images or other data, including apparatus for communication in a wired or wireless network (such as a local or wide area network), other than transmission or reception apparatus of heading 8443, 8525, 8527 or 8528" },
    { code: "8523", desc: "Discs, tapes, solid-state non-volatile storage devices, \"smart cards\" and other media for the recording of sound or of other phenomena, whether or not recorded, including matrices and masters for the production of discs, but excluding products of Chapter 37" },
    { code: "8525", desc: "Transmission apparatus for radio-broadcasting or television, whether or not incorporating reception apparatus or sound recording or reproducing apparatus; television cameras, digital cameras and video camera recorders" },
    { code: "8528", desc: "Monitors and projectors, not incorporating television reception apparatus; reception apparatus for television, whether or not incorporating radio-broadcast receivers or sound or video recording or reproducing apparatus" },
    { code: "8536", desc: "Electrical apparatus for switching or protecting electrical circuits, or for making connections to or in electrical circuits (for example, switches, relays, fuses, surge suppressors, plugs, sockets, lamp-holders and other connectors, junction boxes), for a voltage not exceeding 1 000 V" },
    { code: "8537", desc: "Boards, panels, consoles, desks, cabinets and other bases, equipped with two or more apparatus of heading 8535 or 8536, for electric control or the distribution of electricity, including those incorporating instruments or apparatus of Chapter 90, and numerical control apparatus, other than switching apparatus of heading 8517" },
    { code: "8541", desc: "Diodes, transistors and similar semiconductor devices; photosensitive semiconductor devices, including photovoltaic cells whether or not assembled in modules or made up into panels; light emitting diodes" },
    { code: "8542", desc: "Electronic integrated circuits" },
    { code: "8544", desc: "Insulated (including enamelled or anodised) wire, cable (including co-axial cable) and other insulated electric conductors, whether or not fitted with connectors; optical fibre cables, made up of individually sheathed fibres, whether or not assembled with electric conductors or fitted with connectors" },
    { code: "8701", desc: "Tractors (other than tractors of heading 8709)" },
    { code: "8703", desc: "Motor cars and other motor vehicles principally designed for the transport of persons (other than those of heading 8702), including station wagons and racing cars" },
    { code: "8704", desc: "Motor vehicles for the transport of goods" },
    { code: "8708", desc: "Parts and accessories of the motor vehicles of headings 8701 to 8705" },
    { code: "8802", desc: "Other aircraft (for example, helicopters, aeroplanes); spacecraft (including satellites) and suborbital and spacecraft launch vehicles" },
    { code: "9001", desc: "Optical fibres and optical fibre bundles; optical fibre cables other than those of heading 8544; sheets and plates of polarising material; lenses (including contact lenses), prisms, mirrors and other optical elements, of any material, unmounted, other than such elements of glass not optically worked" },
    { code: "9018", desc: "Instruments and appliances used in medical, surgical, dental or veterinary sciences, including scintigraphic apparatus, other electro-medical apparatus and sight-testing instruments" },
    { code: "9021", desc: "Orthopaedic appliances, including crutches, surgical belts and trusses; splints and other fracture appliances; artificial parts of the body; hearing aids and other appliances which are worn or carried, or implanted in the body, to compensate for a defect or disability" },
    { code: "9026", desc: "Instruments and apparatus for measuring or checking the flow, level, pressure or other variables of liquids or gases (for example, flow meters, level gauges, manometers, heat meters), excluding instruments and apparatus of heading 9014, 9015, 9028 or 9032" },
    { code: "9027", desc: "Instruments and apparatus for physical or chemical analysis (for example, polarimeters, refractometers, spectrometers, gas or smoke analysis apparatus); instruments and apparatus for measuring or checking viscosity, porosity, expansion, surface tension or the like; instruments and apparatus for measuring or checking quantities of heat, sound or light (including exposure meters); microtomes" },
    { code: "9032", desc: "Automatic regulating or controlling instruments and apparatus" },
    { code: "9101", desc: "Wrist-watches, pocket-watches and other watches, including stop-watches, with case of precious metal or of metal clad with precious metal" },
    { code: "9102", desc: "Wrist-watches, pocket-watches and other watches, including stop-watches, other than those of heading 9101" },
    { code: "9401", desc: "Seats (other than those of heading 9402), whether or not convertible into beds, and parts thereof" },
    { code: "9403", desc: "Other furniture and parts thereof" },
    { code: "9405", desc: "Lamps and lighting fittings including searchlights and spotlights and parts thereof, not elsewhere specified or included; illuminated signs, illuminated name-plates and the like, having a permanently fixed light source, and parts thereof not elsewhere specified or included" },
    { code: "9503", desc: "Tricycles, scooters, pedal cars and similar wheeled toys; dolls' carriages; dolls; other toys; reduced-size ('scale') models and similar recreational models, working or not; puzzles of all kinds" },
    { code: "9504", desc: "Video game consoles and machines, articles for funfair, table or parlour games, including pintables, billiards, special tables for casino games and automatic bowling alley equipment" },
    { code: "9506", desc: "Articles and equipment for general physical exercise, gymnastics, athletics, other sports (including table-tennis) or outdoor games, not specified or included elsewhere in this Chapter; swimming pools and paddling pools" }
];
